FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

# Do not exclude man pages & other documentation
RUN rm /etc/dpkg/dpkg.cfg.d/excludes
# Reinstall all currently installed packages in order to get the man pages back
RUN apt-get update && dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -y --reinstall
RUN apt-get install -y less file nano man xxd ssh netcat openssl sudo
RUN cat /dev/urandom | tr -d -c '[:alpha:]'|head -c 1M |fold -w40 > data_tmp.txt
RUN echo "millionth flag{$flag0}" | cat - data_tmp.txt |shuf > data.txt
RUN rm data_tmp.txt

# set the command to run at container start (generally a shell)
CMD bash