FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

RUN  apt-get update && apt-get install -y less file nano man xxd ssh netcat openssl
RUN cat /dev/urandom | tr -d -c '[:alpha:]'|head -c 1M |fold -w40 > data_tmp.txt
RUN echo "millionth flag{$flag0}" | cat - data_tmp.txt |shuf > data.txt
RUN rm data_tmp.txt

# set the command to run at container start (generally a shell)
CMD bash