FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

RUN  apt-get update && apt-get install -y less file nano man xxd ssh netcat openssl sudo
RUN echo "flag{$flag0}" | base64 > data.txt

# set the command to run at container start (generally a shell)
CMD bash