FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

RUN  apt-get update && apt-get install -y less file nano man xxd ssh netcat openssl sudo
RUN [ "/bin/bash", "-c", "mkdir inhere && touch inhere/inhere{01..20}" ]
RUN [ "/bin/bash", "-c", "shred -n 1 -s 1M inhere/inhere{01..20}" ]
RUN echo "flag{$flag0}" | cat - /dev/urandom | tr -d -c '[:print:]\n{}-'|head -c 1M > inhere/inhere12

# set the command to run at container start (generally a shell)
CMD bash