FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

# Do not exclude man pages & other documentation
RUN rm /etc/dpkg/dpkg.cfg.d/excludes
# Reinstall all currently installed packages in order to get the man pages back
RUN apt-get update && dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -y --reinstall
RUN apt-get install -y less file nano man xxd ssh netcat openssl sudo
RUN apt-get install -y openssh-server
RUN adduser --gecos "" --disabled-password bash200
RUN ssh-keygen -N "" -f bash200_rsa_key && mkdir /home/bash200/.ssh && mv bash200_rsa_key.pub /home/bash200/.ssh/authorized_keys
RUN chown bash200:bash200 /home/bash200/.ssh/authorized_keys && chmod 600 /home/bash200/.ssh/authorized_keys
RUN chown $chal_user:$chal_user bash200_rsa_key
RUN [ "/bin/bash", "-c", "chmod 700 /home/*" ]
COPY ssh_shell.sh /usr/bin/ssh_shell.sh
COPY sshd.sh /usr/sshd.sh
RUN mkdir /run/sshd && chmod u+s /usr/sshd.sh
RUN echo "Match User *\n ForceCommand /usr/bin/ssh_shell.sh\n PermitTTY no\n PubkeyAuthentication yes\n AuthorizedKeysFile .ssh/authorized_keys" >> /etc/ssh/sshd_config
RUN echo "flag{$flag0}" > /home/bash200/flag.txt

# set the command to run at container start (generally a shell)
CMD /usr/sshd.sh && bash