FROM ubuntu
ARG flag0=flag
ARG flag1=flag
ARG flag2=flag
ARG flag3=flag
ARG flag4=flag
ARG flag5=flag
ARG flag6=flag
ARG flag7=flag
ARG chal_user=bash

# Do not exclude man pages & other documentation
RUN rm /etc/dpkg/dpkg.cfg.d/excludes
# Reinstall all currently installed packages in order to get the man pages back
RUN apt-get update && dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -y --reinstall
RUN apt-get install -y less file nano man xxd ssh netcat openssl sudo

RUN adduser --gecos "" --disabled-password --home "/home/flag{$flag0}/" $chal_user
WORKDIR /home/flag\{$flag0\}/
RUN touch "flag{$flag1}"
RUN addgroup $flag2
RUN touch just-another-file && chown :$flag2 just-another-file
RUN touch ".flag{$flag3}"
RUN mkdir Documents
RUN echo flag{$flag4} > Documents/secret.txt
RUN echo flag{$flag5} > Documents/file\ with\ spaces.txt
RUN echo flag{$flag6} > Documents/-kebab-
RUN echo -e "bash1 flag{$flag7}" > .bash_history
RUN sed -i "s/^.*PS1='\${debian_chroot.*\$/    PS1='\${debian_chroot:+(\$debian_chroot)}\\u@\\h\\\$ '/" .bashrc
# set the command to run at container start (generally a shell)
CMD bash
