FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

RUN  apt-get update && apt-get install -y less file nano man xxd ssh netcat openssl sudo
RUN apt-get install -y socat
COPY *.sh /usr/
RUN echo "trade-this-for-a-password" > data.txt
RUN sed -i "s/flag{}/flag{$flag0}/" /usr/listen.sh


# set the command to run at container start (generally a shell)
CMD /usr/starter.sh && bash