FROM ubuntu
ARG flag0=flag
ARG chal_user=bash
RUN adduser --gecos "" --disabled-password $chal_user
WORKDIR /home/$chal_user

# Do not exclude man pages & other documentation
RUN rm /etc/dpkg/dpkg.cfg.d/excludes
# Reinstall all currently installed packages in order to get the man pages back
RUN apt-get update && dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -y --reinstall
RUN apt-get install -y less file nano man xxd ssh netcat openssl sudo
RUN apt-get install -y socat
COPY *.sh /usr/
RUN echo "trade-this-for-a-password" > data.txt
RUN sed -i "s/flag{}/flag{$flag0}/" /usr/listen.sh
RUN adduser --gecos "" --disabled-password bash200
RUN [ "/bin/bash", "-c", "chown bash200:bash200 /usr/{listen.sh,starter.sh}" ]
RUN chmod 755 /usr/listen.sh

# set the command to run at container start (generally a shell)
CMD /usr/starter.sh && bash